### ISSUE TITLE
Autoupdating Apps

### ISSUE THREAD

**Issue by prologic** [aklinker1/miasma#44]
I note from the FAQ:

> I don't want to SSH into my device every time I want to update the app version or change an environment variable. Ideally, apps should just update auto-magically (watchtower plugin incoming).

I highly recommend [swarmupdater](https://github.com/codestation/swarm-updater) which I run in all my production Swarm clusters.

I'm even happy to fork it and maintain it 😅

**Comment by aklinker1** [comment]
Thanks for the recommendation! I was considering using watchtower for this, but this might be lighter weight. Is there a public docker image I can run as a plugin? I can't quite tell how to actually run it.

**Comment by prologic** [comment]
> Thanks for the recommendation! I was considering using watchtower for this, but this might be lighter weight. Is there a public docker image I can run as a plugin? I can't quite tell how to actually run it.

Remind me on the weekend... I'll publish an image for it and show you how to run it in Swarm.

**Comment by aklinker1** [comment]
I also found this, that does the same thing: https://github.com/djmaze/shepherd

Thoughts?

**Comment by aklinker1** [comment]
Actually, I doubt either of those services will work... Currently, the service is ran using the image digest, not the image tag, so that it's locked down to a specific version of the image. It's done this way so every node in the cluster is running the same version of the image.

Since we're using the digest, these tools will never tell a service to update, because there's never a newer version of a digest.

---

I see three options here:

1. Custom solution built into Miasma - all the logic for pulling images and restarting apps is already written, we just need to bring in a CRON library and schedule the work.
2. Use a registry with webhooks - the [`registry` image](https://docs.docker.com/registry/configuration/#notifications) has support for this. We make it into a plugin, and bam we're done.
3. Don't auto-upgrade - just force people to include the upgrade command as apart of their publishing process:
   ```bash
   docker build -t my-app:latest .
   docker push my-app:latest
   miasma apps:upgrade -a my-app
   ```

Personally, I think option 2 is the way to go. That way, as soon as I push the image, it gets pulled and the services upgraded.

Option 1 would be nice to keep public images up to date from docker hub, but usually those kinds of apps are things you want to lock down to specific versions and not upgrade, like postgres or redis. I wouldn't want either of those upgrading silently behind the scenes.

Of course, we could have both 1 and 2, but have a setting per app that enables or disabled automatic upgrades. That would cover all cases.

**Comment by prologic** [comment]
Let's build support for 1 and 2
